apiVersion: v1
kind: Secret
metadata:
  name: finops-env
  namespace: finops
type: Opaque
stringData:
  GCP_PROJECT_ID: "ssh-marine"
  GCP_DATASET: "gcp_billing"
  GCP_TABLE: "gcp_billing_export_resource_v1_01D037_3AB34D_12AAE9"
  REQUIRED_LABEL: "env"
  ALERT_THRESHOLD: "90"
  GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/gcp-sa.json"
  SLACK_WEBHOOK: ""
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  FROM_EMAIL: ""
  FINANCE_TEAM_EMAILS: ""
  DEVOPS_TEAM_EMAILS: ""
  PROD_TEAM_EMAILS: ""
---
# GCP service account key — base64 encode your gcp-sa.json and put it here
# Run: base64 -w 0 credentials/gcp-sa.json
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sa-key
  namespace: finops
type: Opaque
data:
  gcp-sa.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3NoLW1hcmluZSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjFkNjI0NzJhOThhYjU0ZTM4M2FiYzQzMzE0MTFjMjdlZGE4NDQ2ZmQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ1drSEJtVnVsQ3VZRVZcbm9lMzJuNGtHZ3lXbFgrZEZta3k0TzFaTU1qYkZsSFJHS1B2bFhSdlFhOE1CbFVWVDMwNzFTajAzSXZsOTRaQzZcbnlTVHV3RDE3MnlwY1lwZjNJNlBwZzZkdStyTzVCTThCN3lEMk9tN2cwb282d3BXbDhnNXJCVExpaUkydytYeEtcbllMRUorajRSd0NDdmR5bnViZFR4RGJ1MWxZWW5NeXVvS2ZqTGlwZVk5cFR5YVBuY1BiZ1k4alR3d2Q0alNmSVBcbkVMV0tkS2xXYkhhUFFpYVV1UXQwcXg2T3FwOWpMQ05sbEd4bHB4VnR0VDFHSmRaTHVIc1ozL3hiQTNwWVpOcUxcbkQ2Q2ZXVTFmWUE0TXJzUlBTK095ZTh6cVBSdVE2L1UwSGNRdE1xWFdoRjQ4ZUN6czh6U2hmdTBYQjRZUXNBdnlcbnJFVUR6UnBaQWdNQkFBRUNnZ0VBUG1rMURsYnNiZ296SmVKdm41RlYzV3N6aWErTlVGNjdlb3F1SlB1VGxLY0tcbjQ2Sk5lQy8yUFpqTnhyUTNmcUxNT2dWQ0JyN3FxSEY5NnM5Q0RlMkdEdmMwUWdOa2RyOUJUS1NVSFA2eXpQamZcblRpL3ZlK0dRNElTbFkrSVE0aTdLSnphS2R6aWZjMEtYY01WUDNaRHJkYlFzV0UrUEJCUm05bHo0K0RZNDI3cEpcbmtMd1JVUXlZMHEyM0dFSTNSbmFIbFFzekdOR0xOSU14cWgvMUxRQ1FXcGVzRVJQNUtMa0xLWlRaNVZvRXFtNE9cbi9ySDBjZy95Y3VmWUlRYUxQTGxRaFc0WGwranpWNVNpNTFpZEE1aTYxYVNCYnZ4azNvMmJoSDJ5WnJjejJ6RWpcbmo3Mmp2SEdLUXhtSGpWMDBxMTZadTBZekJrcTBtc1dZaHpPZTNSZ2hHUUtCZ1FESEs1bkZtSnRpZUNMRVlHbGxcbjNxVmp1WkkwREZOUUJjc1NBZUNDSFZRUmIvNzM3dkorZlY5blZMRXd1V3lnUDVMYWtjK0N1SXM1VzA2TUY1ZndcbjBEY2Fpb3pJSGdZa2tGUDNQaklhcmt3VkJndFdkdDVkanBvYkUxMC9JYkNDdm1XSS9nejJJYVlZVGtJdGlMK1Jcbi9XTnZaWUY3YUozRnM3d2Zvc1FrRXM4UjV3S0JnUURCaG1lbzBDaGFaVkFKdTlockVUS21MRVh2eDJ1TzZBRDVcbm1JSnY5RDZhbnozMHdMQ3BDNzBLcjFPOWhxYVBZL1JxWXdSWFlvdkpwbllLOFQwRlpjQXArTC8yQVZDSWZuZmhcbjlsZkg1NGxKVTZCZ3g4S3VtNVIrb0lDcDB2QU1NMVZNMG85LytzMEExU3pzc1gxeG91clpHYkJnSVVua01rTWtcbjNWOGc2bkZwdndLQmdIWXEzVElLQis3VlBqTnF6RDIvYWpzUHA3bXZzbUpnL1lteWlXUkpTRTZNTnljY29zei9cblQzSThJbUM1TXNTazAxbFFkMkNrWXgzbG1XV3V2ZHdIZlJvSEo5MjNTb2U1QmNoRUkzQUhCMmJWempZL2tsREpcbndZN2MzMDhNaXZBWFRLQ0pzbUQ1dDlUbDRZZW9nWmg1VU55UHlkSFJVUUl5VUNRbzZ0eElPSWp6QW9HQkFJSnVcbjN6RFZVMDFSMlhjbUIwQnFiL08yQlZFTjNIMk4reEkrNnpNZnNJNHdZK2F4ZEtBTERGZkdRYStNc0hnV2kyYWtcbjVBa3Ruei9ERk81ZEY1NnFyTERkT2l4SlNJa21qQkJkSTE3VnZCOFM0Ulk1clFwWVMrWm9zUzlFdjR2SmtXVmNcbnlXRWRuY3hBNGEyS0Z4MWZDK0JWUXg0WGNhRC9DMmd1Vis1c2RSSXJBb0dCQUtJMzMzNXhoUUI1N3hiU2dCY3NcbkhPSGVDdVJBYWdFQkxveXJXV2RNVjlNQ3pCMlBkZlNaYXl1TldhcWVhT2ZoODF2TGlPS1hBYUNVQ1hVeUl6c0JcbmpGL01kSFVvSnd6UnV3WjdqZHFGNC9FTXBYbzNZOENXMDdtU2ZnNEo2Z0FmUldJNXU2ei9EbGJtZmpMbWpPTi9cbnNqQnBBOTlENmpnMnRrSDkrMXFUTVp4bFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInItcmFqcHV0QHNzaC1tYXJpbmUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAzNzg3NTgzNzA4ODQwMjgzOTUyIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9yLXJhanB1dCU0MHNzaC1tYXJpbmUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0=
